templates:
  default:
    position:
      - [0, 0]

styles:
  zone_base:
    pattern: [zone]
    width: 1
    color: black
    dash: []

  zone_line:
    pattern: [zone, line]
    width: 1
    color: green
    dash: [8,2]

  zone_column:
    pattern: [zone, column]
    width: 2
    color: blue
    dash: [10,5]

  zone_page:
    pattern: [zone, page]
    width: 4
    color: red

  text:
    pattern: [text]
    fill: black

  element_p:
    pattern: [element p]
    color: pink
  element_lb:
    pattern: [element lb]
    color: cyan
  element_cb:
    pattern: [element cb]
    color: yellow
  element_pb:
    pattern: [element pb]
    color: magenta
  element_pc:
    pattern: [element pc]
    color: orange
  element_other:
    pattern: [element]
    color: red

profiles:
  default:
    tasks:
      - template: default
        name : text
      - template: default
        name : image
  dev:
    tasks:
      - name : text
        position:
          - [1,0]
          - [2,0]
      - name : image
        max_resolution: 1500
        grayscale: false
        quality: 80
        position:
          - [1,0]
      - name : element
        element:
          - p
        template: default
        position:
          - [0, 0]
          - [1, 0]
          - [2, 0]
      - name : zone
        position:
          - [0, 0]
          - [1, 0]
      
  test-img:
    tasks:
      - name : image
        max_resolution: 1500
        grayscale: false
        quality: 80
        position:
          - [0,0]
  test-zone:
    tasks:
      - name : zone
        zone_type: line
        position:
          - [1, 0]
      - name : zone
        position:
          - [0, 0]
  test-text:
    tasks:
      - name : image
        max_resolution: 1500
        quality: 80 
      - name : text
        template: default

  test-elem:
    tasks:
      - name : image
        max_resolution: 1500
        quality: 80 
      - name : element
        element:
          - p
        template: default
        position:
          - [0, 0]
          - [1, 0]
      - name: text
        template: default
        position:
          - [1, 0]

active_profile: dev